version: '3.6'
services:
  api:
    build: .
    image: joke-api
    container_name: joke-api
    restart: always
    ports:
      - 8001:8001
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306

  mysql:
    image: mysql:5
    container_name: joke-sql
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
      - ./src/db/:/docker-entrypoint-initdb.d
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    

volumes:
  mysql-data:
    name: joke-mysql-data